### ISSUE TITLE
基本功能不足

### ISSUE THREAD

**Issue by laishaolin** [lgf196/JoL-player#11]
视频没有自动播放功能

**Comment by lgf196** [comment]
在最新版的Chrome浏览器（以及所有以Chromium为内核的浏览器）中，已不再允许自动播放音频和视频。（Google的某些做法还真是令开发者不爽）。就算你为video或audio标签设置了`autoplay`属性也一样不能自动播放

这是因为，Chrome只允许用户对网页进行主动触发后才可自动播放音频和视频。其实，严格地来说，是Chrome不允许在用户对网页进行触发之前播放音频，而视频其实是不受限制的。但因为视频文件同样包含了音频，所以也一同被禁止了。Chrome这样做的目的是为了防止开发者滥用自动播放功能而对用户产生骚扰

自动播放功能是有的，但是当时考虑到如上问题，就去掉了，我看下后期要不要加上自动播放的

如果你这边急切的需要这个功能，也是可以的，用ref来操作原生对象，设置静音，这样是可以自动播放的
