### ISSUE TITLE
测试用例代码的时候出现Cannot read properties of null (reading 'useRef')

### ISSUE THREAD

**Issue by 1144075799** [lgf196/JoL-player#15]
<img width="608" alt="image" src="https://user-images.githubusercontent.com/38463468/194742207-48cf93b7-24dc-447b-ae27-58f34e62f330.png">
<img width="701" alt="image" src="https://user-images.githubusercontent.com/38463468/194742225-c260970c-3743-4c0b-bc03-dbd004854971.png">
希望可以得到你的回复

**Comment by lgf196** [comment]
请参考这个demo:[https://codesandbox.io/s/i9vy4](https://codesandbox.io/s/i9vy4)

最新版本v3.5建议用
```
import  {JoLPlayer}  from "jol-player"
```
这样来引入

**Comment by 1144075799** [comment]
<img width="1048" alt="image" src="https://user-images.githubusercontent.com/38463468/194812776-0a6d3571-7737-47f1-8000-afc446351df2.png">
还是不行

**Comment by lgf196** [comment]
如果使用的是react版本18+,那么请用插件v3+版本的，如果是小于18版本的，请用该插件v2+版本的

参考这个demo: https://codesandbox.io/s/i9vy4
