### ISSUE TITLE
能不能加个自适应宽高的？

### ISSUE THREAD

**Issue by zhengtan2003** [lgf196/JoL-player#16]
少数情况下会有这个需求

**Comment by lgf196** [comment]
感谢反馈，后期版本，`width`，`height`属性支持`auto`参数
```
type auto = 'auto ';
type styleFormat<T> = T |  auto ;
```

**Comment by zhengtan2003** [comment]
> 感谢反馈，后期版本，`width`，`height`属性支持`auto`参数
> 
> ```
> type auto = 'auto ';
> type styleFormat<T> = T |  auto ;
> ```

对对对，就是这个意思

**Comment by lgf196** [comment]
![image](https://user-images.githubusercontent.com/29600558/201880544-8889c942-5be1-425c-811b-2ae1c46545b5.png)
升级到最新版本`v4.0.0`
