### ISSUE TITLE
建议控制器隐藏逻辑优化

### ISSUE THREAD

**Issue by jemmy-tang** [lgf196/JoL-player#21]
目前控制器仅支持操作后延迟隐藏，暂停阶段也会隐藏的话使用非常不方便，建议暂停阶段保持显示控制器及进度条。

**Comment by lgf196** [comment]
其实大部分视频网站，都是这样的逻辑的，B站，腾讯视频等，一旦暂停了，过个几秒不动，就会自动隐藏，鼠标一动，就会出现，这样做的目的是为了，更好突出视频主体，而不是控制器等，有时候，没有任何操作，控制器一直存在，会造成一个干扰
