### ISSUE TITLE
能否支持播放按钮下自定义layer的渲染

### ISSUE THREAD

**Issue by Paleless** [lgf196/JoL-player#23]
大致是这样的需求：
     需要自定义一些装饰组件，能够根据播放时间修改组件的动画效果
      但是这个装饰动画层需要在视频层级之上，但是不能覆盖在播放按钮那一层
      如果直接自己做mask盖在joi-player上的话能实现效果，但是会覆盖播放按钮
     能够加一个prop支持吗

**Comment by lgf196** [comment]
可以在我的基础上进行二次开发
