### ISSUE TITLE
Cannot read properties of null (reading 'play')

### ISSUE THREAD

**Issue by MIN202299** [lgf196/JoL-player#24]
组件挂载时调用play()方法报错；
<img width="491" alt="image" src="https://github.com/lgf196/JoL-player/assets/105197349/46c87e2f-e69f-4669-9499-d6bb62e015b5">

例如：
```js
 useEffect(() => {
    console.log(`videoRef.current`, videoRef.current);
    videoRef.current.play();  //  videoRef.current 不是 null
  }, [videoRef.current]);
```
能否给一个方法监听，何时视频可以播放

**Comment by lgf196** [comment]
v5版本正在更新中，会加上一个onReady方法

**Comment by lgf196** [comment]
```
useEffect(() => {
    console.log(`videoRef.current`, videoRef.current);
    videoRef.current.play();  //  videoRef.current 不是 null
  }, [videoRef.current]);
```
不建议在useEffect中这样使用videoRef.current.play();来调取，useEffect使用的不当，会造成播放器死循环的情况，无法准确定位

**Comment by lgf196** [comment]
关于如何使用ref来调用，请查看如下案例[https://codesandbox.io/s/bold-night-i9vy4?file=/src/App.tsx](https://codesandbox.io/s/bold-night-i9vy4?file=/src/App.tsx)
