### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by pateljoel** [lgf196/JoL-player#4]
i get invalid hook call on the example alone

**Comment by lgf196** [comment]
Can you provide a case?

**Comment by pateljoel** [comment]
<img width="1438" alt="jolplayer-issue" src="https://user-images.githubusercontent.com/64401775/148054384-a3b58c24-0332-4505-8065-fb83a2db59ef.png">

```jsx
import React from 'react';
import JoLPlayer from "jol-player";

const App = () => (
  <>
    <JoLPlayer
        option={{
          videoType: 'hls',
          videoSrc:"https://media.vimejs.com/hls/index.m3u8",
          width: 750,
          height: 420,
        }}
      />
  </>
);

export default App;
```

https://jolplayerdemo.joelptl.repl.co

**Comment by lgf196** [comment]
Please try it with `npm install`
