### ISSUE TITLE
反馈两个问题

### ISSUE THREAD

**Issue by a1782680475** [lgf196/JoL-player#5]
第一，在antd pro里面的drawer组件里面播放hls视频是不行的，一直在重复加载。
第二，播放器下方的控制组件最好处理一下，比如加个模糊背景之类，否则容易和视频内容混在一起导致控件难以辨认。

**Comment by lgf196** [comment]
1：m3u8类型的视频确实播放的有点慢，但是是可以播放的
2：后面版本，加一个磨砂背景，感谢反馈

**Comment by a1782680475** [comment]
> 
我的意思是在antd pro的Drawer里面，不是慢的问题，是根本无法播放的，会发现m3u8无限重复加载，但是我放在弹窗里是没问题的，这个麻烦你测试一下。
对了，还有一个问题是关于宽度的问题，现在宽度只支持number像素设置，能否像antd一样增加字符串的宽度设置，或者说默认宽度非必填，默认是容器宽度100%？

**Comment by lgf196** [comment]
OK,我看看
