### ISSUE TITLE
reset影响到其他样式

### ISSUE THREAD

**Issue by zimv** [lgf196/JoL-player#8]
能否控制一下所有的css作用域，引入库之后 会影响到其他样式

**Comment by lgf196** [comment]
有可能是初始化默认样式`reset.css`引起的，预计6月份修复，换成`css-module`

**Comment by lgf196** [comment]
稍等，下班了马上合并你的，看下，马上更新版本

**Comment by zimv** [comment]
羡慕，这么早下班

**Comment by lgf196** [comment]
已修复下载最新版本`v3.1.0`

**Comment by zimv** [comment]
感谢发版～
就是你的MR方式有点...
